swagger: '2.0'
info:
  version: 1.0.0
  title: koa-oai-mongoose example
consumes:
  - application/json
produces:
  - application/json
basePath: /api
paths:
  /user/auth:
    post:
      tags:
        - user
      description: find a luck user
      x-oai-controller:
        - file: user
          handler: auth
      parameters:
        - data: data
          in: body
          type: object
          required: true
      responses:
        200:
          description: user login